//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UVStudio {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SetInfoFrm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SetInfoFrm() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UVStudio.SetInfoFrm", typeof(SetInfoFrm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного Bottom, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles btnOK_Anchor {
            get {
                object obj = ResourceManager.GetObject("btnOK.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.FlatStyle, аналогичного Flat.
        /// </summary>
        internal static System.Windows.Forms.FlatStyle btnOK_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("btnOK.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font btnOK_Font {
            get {
                object obj = ResourceManager.GetObject("btnOK.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode btnOK_ImeMode {
            get {
                object obj = ResourceManager.GetObject("btnOK.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=12,Y=467}.
        /// </summary>
        internal static System.Drawing.Point btnOK_Location {
            get {
                object obj = ResourceManager.GetObject("btnOK.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.Padding, аналогичного {Left=3,Top=6,Right=3,Bottom=6}.
        /// </summary>
        internal static System.Windows.Forms.Padding btnOK_Margin {
            get {
                object obj = ResourceManager.GetObject("btnOK.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=618, Height=50}.
        /// </summary>
        internal static System.Drawing.Size btnOK_Size {
            get {
                object obj = ResourceManager.GetObject("btnOK.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 134.
        /// </summary>
        internal static int btnOK_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnOK.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font label11_Font {
            get {
                object obj = ResourceManager.GetObject("label11.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode label11_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label11.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=581,Y=223}.
        /// </summary>
        internal static System.Drawing.Point label11_Location {
            get {
                object obj = ResourceManager.GetObject("label11.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=49, Height=40}.
        /// </summary>
        internal static System.Drawing.Size label11_Size {
            get {
                object obj = ResourceManager.GetObject("label11.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 250.
        /// </summary>
        internal static int label11_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label11.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;.
        /// </summary>
        internal static string label11_Text {
            get {
                return ResourceManager.GetString("label11.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleRight.
        /// </summary>
        internal static System.Drawing.ContentAlignment label11_TextAlign {
            get {
                object obj = ResourceManager.GetObject("label11.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного Top, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles label12_Anchor {
            get {
                object obj = ResourceManager.GetObject("label12.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode label12_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label12.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=8,Y=271}.
        /// </summary>
        internal static System.Drawing.Point label12_Location {
            get {
                object obj = ResourceManager.GetObject("label12.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=624, Height=2}.
        /// </summary>
        internal static System.Drawing.Size label12_Size {
            get {
                object obj = ResourceManager.GetObject("label12.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 249.
        /// </summary>
        internal static int label12_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label12.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font label13_Font {
            get {
                object obj = ResourceManager.GetObject("label13.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode label13_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label13.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=8,Y=223}.
        /// </summary>
        internal static System.Drawing.Point label13_Location {
            get {
                object obj = ResourceManager.GetObject("label13.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=623, Height=40}.
        /// </summary>
        internal static System.Drawing.Size label13_Size {
            get {
                object obj = ResourceManager.GetObject("label13.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 248.
        /// </summary>
        internal static int label13_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label13.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 考试时间.
        /// </summary>
        internal static string label13_Text {
            get {
                return ResourceManager.GetString("label13.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleLeft.
        /// </summary>
        internal static System.Drawing.ContentAlignment label13_TextAlign {
            get {
                object obj = ResourceManager.GetObject("label13.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font label15_Font {
            get {
                object obj = ResourceManager.GetObject("label15.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode label15_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label15.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=581,Y=281}.
        /// </summary>
        internal static System.Drawing.Point label15_Location {
            get {
                object obj = ResourceManager.GetObject("label15.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=49, Height=40}.
        /// </summary>
        internal static System.Drawing.Size label15_Size {
            get {
                object obj = ResourceManager.GetObject("label15.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 254.
        /// </summary>
        internal static int label15_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label15.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;.
        /// </summary>
        internal static string label15_Text {
            get {
                return ResourceManager.GetString("label15.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleRight.
        /// </summary>
        internal static System.Drawing.ContentAlignment label15_TextAlign {
            get {
                object obj = ResourceManager.GetObject("label15.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного False.
        /// </summary>
        internal static bool label15_Visible {
            get {
                object obj = ResourceManager.GetObject("label15.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного Top, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles label16_Anchor {
            get {
                object obj = ResourceManager.GetObject("label16.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode label16_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label16.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=8,Y=329}.
        /// </summary>
        internal static System.Drawing.Point label16_Location {
            get {
                object obj = ResourceManager.GetObject("label16.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=624, Height=2}.
        /// </summary>
        internal static System.Drawing.Size label16_Size {
            get {
                object obj = ResourceManager.GetObject("label16.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 253.
        /// </summary>
        internal static int label16_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label16.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного False.
        /// </summary>
        internal static bool label16_Visible {
            get {
                object obj = ResourceManager.GetObject("label16.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font label17_Font {
            get {
                object obj = ResourceManager.GetObject("label17.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode label17_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label17.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=8,Y=281}.
        /// </summary>
        internal static System.Drawing.Point label17_Location {
            get {
                object obj = ResourceManager.GetObject("label17.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=623, Height=40}.
        /// </summary>
        internal static System.Drawing.Size label17_Size {
            get {
                object obj = ResourceManager.GetObject("label17.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 252.
        /// </summary>
        internal static int label17_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label17.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 其他.
        /// </summary>
        internal static string label17_Text {
            get {
                return ResourceManager.GetString("label17.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleLeft.
        /// </summary>
        internal static System.Drawing.ContentAlignment label17_TextAlign {
            get {
                object obj = ResourceManager.GetObject("label17.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного False.
        /// </summary>
        internal static bool label17_Visible {
            get {
                object obj = ResourceManager.GetObject("label17.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного Top, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles label5_Anchor {
            get {
                object obj = ResourceManager.GetObject("label5.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode label5_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label5.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=8,Y=152}.
        /// </summary>
        internal static System.Drawing.Point label5_Location {
            get {
                object obj = ResourceManager.GetObject("label5.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=624, Height=2}.
        /// </summary>
        internal static System.Drawing.Size label5_Size {
            get {
                object obj = ResourceManager.GetObject("label5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 246.
        /// </summary>
        internal static int label5_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label5.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного Top, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles label7_Anchor {
            get {
                object obj = ResourceManager.GetObject("label7.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode label7_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label7.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=8,Y=213}.
        /// </summary>
        internal static System.Drawing.Point label7_Location {
            get {
                object obj = ResourceManager.GetObject("label7.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=624, Height=2}.
        /// </summary>
        internal static System.Drawing.Size label7_Size {
            get {
                object obj = ResourceManager.GetObject("label7.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 240.
        /// </summary>
        internal static int label7_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label7.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font label8_Font {
            get {
                object obj = ResourceManager.GetObject("label8.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode label8_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label8.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=581,Y=105}.
        /// </summary>
        internal static System.Drawing.Point label8_Location {
            get {
                object obj = ResourceManager.GetObject("label8.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=49, Height=40}.
        /// </summary>
        internal static System.Drawing.Size label8_Size {
            get {
                object obj = ResourceManager.GetObject("label8.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 247.
        /// </summary>
        internal static int label8_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label8.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;.
        /// </summary>
        internal static string label8_Text {
            get {
                return ResourceManager.GetString("label8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleRight.
        /// </summary>
        internal static System.Drawing.ContentAlignment label8_TextAlign {
            get {
                object obj = ResourceManager.GetObject("label8.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного Top, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles label9_Anchor {
            get {
                object obj = ResourceManager.GetObject("label9.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode label9_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label9.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=8,Y=93}.
        /// </summary>
        internal static System.Drawing.Point label9_Location {
            get {
                object obj = ResourceManager.GetObject("label9.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=624, Height=2}.
        /// </summary>
        internal static System.Drawing.Size label9_Size {
            get {
                object obj = ResourceManager.GetObject("label9.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 239.
        /// </summary>
        internal static int label9_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label9.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lbl1_Font {
            get {
                object obj = ResourceManager.GetObject("lbl1.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode lbl1_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbl1.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=8,Y=46}.
        /// </summary>
        internal static System.Drawing.Point lbl1_Location {
            get {
                object obj = ResourceManager.GetObject("lbl1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=623, Height=40}.
        /// </summary>
        internal static System.Drawing.Size lbl1_Size {
            get {
                object obj = ResourceManager.GetObject("lbl1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 238.
        /// </summary>
        internal static int lbl1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbl1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 组别.
        /// </summary>
        internal static string lbl1_Text {
            get {
                return ResourceManager.GetString("lbl1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleLeft.
        /// </summary>
        internal static System.Drawing.ContentAlignment lbl1_TextAlign {
            get {
                object obj = ResourceManager.GetObject("lbl1.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lbl11_Font {
            get {
                object obj = ResourceManager.GetObject("lbl11.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode lbl11_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbl11.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=581,Y=46}.
        /// </summary>
        internal static System.Drawing.Point lbl11_Location {
            get {
                object obj = ResourceManager.GetObject("lbl11.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=49, Height=40}.
        /// </summary>
        internal static System.Drawing.Size lbl11_Size {
            get {
                object obj = ResourceManager.GetObject("lbl11.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 241.
        /// </summary>
        internal static int lbl11_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbl11.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;.
        /// </summary>
        internal static string lbl11_Text {
            get {
                return ResourceManager.GetString("lbl11.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleRight.
        /// </summary>
        internal static System.Drawing.ContentAlignment lbl11_TextAlign {
            get {
                object obj = ResourceManager.GetObject("lbl11.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lbl2_Font {
            get {
                object obj = ResourceManager.GetObject("lbl2.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode lbl2_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbl2.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=8,Y=165}.
        /// </summary>
        internal static System.Drawing.Point lbl2_Location {
            get {
                object obj = ResourceManager.GetObject("lbl2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=623, Height=40}.
        /// </summary>
        internal static System.Drawing.Size lbl2_Size {
            get {
                object obj = ResourceManager.GetObject("lbl2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 237.
        /// </summary>
        internal static int lbl2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbl2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 工位号.
        /// </summary>
        internal static string lbl2_Text {
            get {
                return ResourceManager.GetString("lbl2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleLeft.
        /// </summary>
        internal static System.Drawing.ContentAlignment lbl2_TextAlign {
            get {
                object obj = ResourceManager.GetObject("lbl2.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lbl22_Font {
            get {
                object obj = ResourceManager.GetObject("lbl22.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode lbl22_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbl22.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=581,Y=165}.
        /// </summary>
        internal static System.Drawing.Point lbl22_Location {
            get {
                object obj = ResourceManager.GetObject("lbl22.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=49, Height=40}.
        /// </summary>
        internal static System.Drawing.Size lbl22_Size {
            get {
                object obj = ResourceManager.GetObject("lbl22.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 243.
        /// </summary>
        internal static int lbl22_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbl22.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;.
        /// </summary>
        internal static string lbl22_Text {
            get {
                return ResourceManager.GetString("lbl22.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleRight.
        /// </summary>
        internal static System.Drawing.ContentAlignment lbl22_TextAlign {
            get {
                object obj = ResourceManager.GetObject("lbl22.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lbldesc_Font {
            get {
                object obj = ResourceManager.GetObject("lbldesc.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode lbldesc_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbldesc.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=378,Y=281}.
        /// </summary>
        internal static System.Drawing.Point lbldesc_Location {
            get {
                object obj = ResourceManager.GetObject("lbldesc.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=197, Height=40}.
        /// </summary>
        internal static System.Drawing.Size lbldesc_Size {
            get {
                object obj = ResourceManager.GetObject("lbldesc.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 255.
        /// </summary>
        internal static int lbldesc_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbldesc.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleRight.
        /// </summary>
        internal static System.Drawing.ContentAlignment lbldesc_TextAlign {
            get {
                object obj = ResourceManager.GetObject("lbldesc.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного False.
        /// </summary>
        internal static bool lbldesc_Visible {
            get {
                object obj = ResourceManager.GetObject("lbldesc.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblEditright_Font {
            get {
                object obj = ResourceManager.GetObject("lblEditright.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode lblEditright_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lblEditright.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=8,Y=104}.
        /// </summary>
        internal static System.Drawing.Point lblEditright_Location {
            get {
                object obj = ResourceManager.GetObject("lblEditright.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=623, Height=40}.
        /// </summary>
        internal static System.Drawing.Size lblEditright_Size {
            get {
                object obj = ResourceManager.GetObject("lblEditright.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 245.
        /// </summary>
        internal static int lblEditright_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblEditright.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 考场.
        /// </summary>
        internal static string lblEditright_Text {
            get {
                return ResourceManager.GetString("lblEditright.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleLeft.
        /// </summary>
        internal static System.Drawing.ContentAlignment lblEditright_TextAlign {
            get {
                object obj = ResourceManager.GetObject("lblEditright.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblgroup_Font {
            get {
                object obj = ResourceManager.GetObject("lblgroup.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode lblgroup_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lblgroup.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=343,Y=46}.
        /// </summary>
        internal static System.Drawing.Point lblgroup_Location {
            get {
                object obj = ResourceManager.GetObject("lblgroup.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=232, Height=40}.
        /// </summary>
        internal static System.Drawing.Size lblgroup_Size {
            get {
                object obj = ResourceManager.GetObject("lblgroup.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 242.
        /// </summary>
        internal static int lblgroup_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblgroup.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleRight.
        /// </summary>
        internal static System.Drawing.ContentAlignment lblgroup_TextAlign {
            get {
                object obj = ResourceManager.GetObject("lblgroup.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblid_Font {
            get {
                object obj = ResourceManager.GetObject("lblid.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode lblid_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lblid.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=343,Y=165}.
        /// </summary>
        internal static System.Drawing.Point lblid_Location {
            get {
                object obj = ResourceManager.GetObject("lblid.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=232, Height=40}.
        /// </summary>
        internal static System.Drawing.Size lblid_Size {
            get {
                object obj = ResourceManager.GetObject("lblid.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 244.
        /// </summary>
        internal static int lblid_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblid.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleRight.
        /// </summary>
        internal static System.Drawing.ContentAlignment lblid_TextAlign {
            get {
                object obj = ResourceManager.GetObject("lblid.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblroom_Font {
            get {
                object obj = ResourceManager.GetObject("lblroom.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode lblroom_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lblroom.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=343,Y=105}.
        /// </summary>
        internal static System.Drawing.Point lblroom_Location {
            get {
                object obj = ResourceManager.GetObject("lblroom.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=232, Height=40}.
        /// </summary>
        internal static System.Drawing.Size lblroom_Size {
            get {
                object obj = ResourceManager.GetObject("lblroom.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 256.
        /// </summary>
        internal static int lblroom_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblroom.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleRight.
        /// </summary>
        internal static System.Drawing.ContentAlignment lblroom_TextAlign {
            get {
                object obj = ResourceManager.GetObject("lblroom.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lbltime_Font {
            get {
                object obj = ResourceManager.GetObject("lbltime.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode lbltime_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lbltime.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=343,Y=223}.
        /// </summary>
        internal static System.Drawing.Point lbltime_Location {
            get {
                object obj = ResourceManager.GetObject("lbltime.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=232, Height=40}.
        /// </summary>
        internal static System.Drawing.Size lbltime_Size {
            get {
                object obj = ResourceManager.GetObject("lbltime.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 251.
        /// </summary>
        internal static int lbltime_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbltime.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleRight.
        /// </summary>
        internal static System.Drawing.ContentAlignment lbltime_TextAlign {
            get {
                object obj = ResourceManager.GetObject("lbltime.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Microsoft YaHei, Size=14, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblTitle_Font {
            get {
                object obj = ResourceManager.GetObject("lblTitle.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode lblTitle_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lblTitle.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=140,Y=6}.
        /// </summary>
        internal static System.Drawing.Point lblTitle_Location {
            get {
                object obj = ResourceManager.GetObject("lblTitle.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=342, Height=31}.
        /// </summary>
        internal static System.Drawing.Size lblTitle_Size {
            get {
                object obj = ResourceManager.GetObject("lblTitle.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 133.
        /// </summary>
        internal static int lblTitle_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblTitle.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 用户信息.
        /// </summary>
        internal static string lblTitle_Text {
            get {
                return ResourceManager.GetString("lblTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.ContentAlignment, аналогичного MiddleCenter.
        /// </summary>
        internal static System.Drawing.ContentAlignment lblTitle_TextAlign {
            get {
                object obj = ResourceManager.GetObject("lblTitle.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
    }
}
